import mongoose from 'mongoose';

const incidentSchema = new mongoose.Schema(
  {
    monitorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Monitor',
      required: true,
      index: true, // Index for faster queries by monitorId
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    status: {
      type: String,
      enum: ['ONGOING', 'RESOLVED'],
      default: 'ONGOING',
    },
    startTime: {
      type: Date,
      // default: Date.now
      required: true,
    },
    endTime: {
      type: Date,
      default: null,
    },
    duration: {
      type: Number, // Duration in seconds
      default: 0,
    },
    reason: {
      type: String, //e.g. "ECONNREFUSED", "ETIMEDOUT", "HTTP_500", etc.
    },
    aiSummary: {
      type: String, //Summary of the incident generated by AI
    },
  },
  { timestamps: true }
);

//Compound index to optimize queries for ongoing incidents of a monitor
incidentSchema.index({ monitorId: 1, status: 1 }); // Index to optimize queries by monitor and time

//Auto duration calculation when resolving an incident.
//Mongoose 9 dropped callback-style `next`; a synchronous hook just returns.
incidentSchema.pre('save', function () {
  if (this.startTime && this.endTime) {
    this.duration = Math.floor((this.endTime - this.startTime) / 1000); // Duration in seconds
  }
});

const incidentModel = mongoose.model('Incident', incidentSchema);

export default incidentModel;
