import mongoose from 'mongoose';

const incidentSchema = new mongoose.Schema(
  {
    monitorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Monitor',
    },
    status: {
      type: String,
      enum: ['ONGOING', 'RESOLVED'],
      default: 'ONGOING',
    },
    startTime: {
      type: Date,
      // default: Date.now
      required: true,
    },
    endTime: {
      type: Date,
      required: true,
    },
    duration: {
      type: Number, // Duration in seconds
      default: 0,
    },
    reason: {
      type: String, //e.g. "ECONNREFUSED", "ETIMEDOUT", "HTTP_500", etc.
    },
    aiSummary: {
      type: String, //Summary of the incident generated by AI
    },
  },
  { timestamps: true }
);

incidentSchema.index({ monitorId: 1, status: 1 }); // Index to optimize queries by monitor and time

const incidentModel = mongoose.model('Incident', incidentSchema);

export default incidentModel;
